### ISSUE TITLE
Add: Config options to slow down animal breeding

### ISSUE THREAD

**Issue by James103** [orlouge/no-mob-farms#4]
Currently, a player can breed a single animal (pig, cow, sheep, bee, horse, etc) every 5 minutes, with babies taking up to 20 minutes to grow. This may be too fast for some players, especially given that with enough animals (at least 600), a single player can continuously breed animals for as long as they have the breeding item.

### Animal Farm Nerf
`animal_breeding_cooldown`: Adds to the breeding cooldown (in ticks) for an animal after it finishes breeding.
`animal_growth_cooldown`: Adds to the time required for a baby animal to grow.

Note that the above settings add (subject to change) to the breeding and growth cooldown. To get the actual time interval,
* Between breeding cycles: Add 6000 (5 minutes) to `animal_breeding_cooldown`.
* For an animal's growth cycle: Add 24000 (20 minutes) to `animal_breeding_cooldown`.

For example:
* 20-minute breeding and 1-hour growth (slow):
	* Set `animal_breeding_cooldown` to 24000 - 6000 = 18000.
	* Set `animal_growth_cooldown` to 72000 - 24000 = 48000.
* 60-minute breeding and 3-hour growth (very slow):
	* Set `animal_breeding_cooldown` to 72000 - 6000 = 66000.
	* Set `animal_growth_cooldown` to 216000 - 24000 = 192000.

**Comment by orlouge** [comment]
This falls out of the scope of this mod, which is meant to stop automated mob farms, not normal ones. I might add a feature against villager-based crop farms, which would make it harder to breed so many animals, but that has low priority.

**Comment by orlouge** [comment]
It seems that ServerCore has an option to block animal and villager breeding if there are too many entities of the same type nearby.
